/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type AppPublicTaskPriority = 'high' | 'low' | 'medium';

export type AppPublicTaskStatus = 'completed' | 'in_progress' | 'pending';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppPrivateUserSecrets {
  password_hash: string;
  user_id: string;
}

export interface AppPublicTasks {
  created_at: Generated<Timestamp>;
  description: string | null;
  due_date: Timestamp | null;
  id: Generated<string>;
  owner_id: string;
  priority: Generated<AppPublicTaskPriority>;
  status: Generated<AppPublicTaskStatus>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface AppPublicUsers {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface GraphileMigrateCurrent {
  content: string;
  date: Generated<Timestamp>;
  filename: Generated<string>;
}

export interface GraphileMigrateMigrations {
  date: Generated<Timestamp>;
  filename: string;
  hash: string;
  previous_hash: string | null;
}

export interface DB {
  'app_private.user_secrets': AppPrivateUserSecrets;
  'app_public.tasks': AppPublicTasks;
  'app_public.users': AppPublicUsers;
  'graphile_migrate.current': GraphileMigrateCurrent;
  'graphile_migrate.migrations': GraphileMigrateMigrations;
}
